from enum import StrEnum


class DocumentStage(StrEnum):
    REGISTERED = "REGISTERED"
    SECURITY_VALIDATED = "SECURITY_VALIDATED"
    PARSED = "PARSED"
    CLASSIFIED = "CLASSIFIED"
    EXTRACTED = "EXTRACTED"
    INDEXED = "INDEXED"
    READY_FOR_OFFICER_REVIEW = "READY_FOR_OFFICER_REVIEW"


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCEEDED = "SUCCEEDED"
    FAILED_MANUAL_REVIEW = "FAILED_MANUAL_REVIEW"
    SUPERSEDED = "SUPERSEDED"


class FactDisposition(StrEnum):
    ACCEPTED = "ACCEPTED"
    CORRECTED = "CORRECTED"
    ABSENT = "ABSENT"
    UNREADABLE = "UNREADABLE"


class GapStatus(StrEnum):
    PROVISIONAL = "PROVISIONAL"
    FORMAL = "FORMAL"
    RESOLVED = "RESOLVED"
    STALE = "STALE"
